### ISSUE TITLE
[Hunter] Pets (Crucial)

### ISSUE THREAD

**Issue by Schnockers** [AnetheronWoW/Anetheron#1]
As soon as you tame a pet (I have tamed a Boar south of Orgrimmar) it is instantly level 70, Loyality level 6 (maxed) and is happy (no need to be fed)
I have not tried yet with other pets but I assume this is set for every pet tamed.

**Comment by Schnockers** [comment]
Confirmed with a cat. 
Cat was level 23. After taming it instantly became level 70, level 6 in loyality and Well Fed (Happy)

**Comment by PredatorAnetheron** [comment]
Fixed
