### ISSUE TITLE
southsea pirates in tanaris

### ISSUE THREAD

**Issue by brian525** [AnetheronWoW/Anetheron#11]
in lost rigger cove seems as the southsea pirates and freebooters wait their turn to attack my pet when i charge the tent area. outside the walls

i did some testing while grinding and found. the freebooter mob next to the tent needs the scripting changed.

1.i attack pirate, freebooter stays there.
2. i attack freebooter and the pirate charges my pet like normal.

it seems like all freebooters have issues. they aggro but stand still even inside the walls.

**Comment by PredatorAnetheron** [comment]
Fix will be added after the next restart
