### ISSUE TITLE
Shdow Priest Replenishment bugged

### ISSUE THREAD

**Issue by Tihifnis** [AnetheronWoW/Anetheron#14]
Replenishment is supposed to give 1% of maximum mana per 5 sec. gives way less mana and i think more procs than intended, combat log included in picture
![unavngivet](https://cloud.githubusercontent.com/assets/25668946/22795023/727e2540-eef5-11e6-8ce8-a6f891b46356.png)

**Comment by PredatorAnetheron** [comment]
Working as intended

14518 = 145,18  (1%)

Gains per second 29 * 15 = 435

435 / 3 (every 5 sec) = 145
