### ISSUE TITLE
(Hunter) Taming Quest, Orc

### ISSUE THREAD

**Issue by SingHarmony** [AnetheronWoW/Anetheron#18]
Can't seem to complete the quest "Taming the beast". You have to use a taming rod to tame an armored scorpid. I use the Taming rod on the scorpid, it cast all the way threw and then nothing happens.

**Comment by PredatorAnetheron** [comment]
Works for me, please close wow and remove your cache file.

![image](https://cloud.githubusercontent.com/assets/25508607/23123982/f8dd08fe-f76a-11e6-865d-b9fd2a7a1b47.png)
