### ISSUE TITLE
Auction House (VERY IMPORTANT)

### ISSUE THREAD

**Issue by Berzerker27** [AnetheronWoW/Anetheron#22]
Dear Moderator,

MSV (Merchant Sell Value)
AH (Auction House)

**Fixing this is key to having a thriving economy.**

The auction house deposits in Stormwind are twice the suggested bidding price, which is 300% MSV at 48Hrs. This leads me to believe that the Faction AH's 'think' they are neutral AH's. Regular Rates are: 15% MSV per 12Hrs (faction AH) and 75% MSV per 12 Hrs (neutral AH).

**If an epic item whose vendor sell price is say, 8G. To put it up for a 48Hr auction _should_ cost 4G when right now it costs 24G!!! You do not get this money back unless someone buys the item!**

Thanks,

Greg

Example Below:

43.9s MSV 

[43.9]x[0.15]x[Duration/12] = 26.34s

This items deposit should be: 26.34s
When its actual deposit is over 1.3G

![ah deposit](https://cloud.githubusercontent.com/assets/25837362/23053825/5e3e9750-f4b2-11e6-8079-d3a85091e1e4.png)

**Comment by PredatorAnetheron** [comment]
Thanks for reporting, fixed.
