### ISSUE TITLE
Summon stone  + VOA

### ISSUE THREAD

**Issue by holyfantasy** [AnetheronWoW/Anetheron#23]
Summmon stone near Icecrown Citadel is not spawned. Could you please spawn it as it easens up everything. 

Double check the boss in VOA Stone Watcher for the Rock shower spell as it seems it is not doing DMG to the targeted player as such.

**Comment by losmy** [comment]
I can help with your first problem. The summoning stone is about 100 yards to the left as you leave ice crown citadel raid.
