### ISSUE TITLE
Ahn'kahet: The Old Kingdom etc.

### ISSUE THREAD

**Issue by KlliMlli** [AnetheronWoW/Anetheron#36]
In Ahn'kahet: The Old Kingdom there is boss called Jedoga Shadowseeker and his 2nd phase is bugged. Mobs doesnt move and he just stays up in air.

There is also still problem with Kirin tor towers stairs

Feral druids jump in wg is also a pit of an problem, they shouldnt be able to jump so high up.

Also there is a problem with some bosses, that if you start autoattacking them far away (even out of range of pull) you still pull them, its rare but has happened few times now in PoS Ick boss.

I would appreciate if you could take a check for these bugs.

Have nice days, KlliMlli

**Comment by ATTtheGM** [comment]
Please separate all the reports, and reopen the again.
