### ISSUE TITLE
Characters Profs, Skills Ect. Gone

### ISSUE THREAD

**Issue by Facade1** [AnetheronWoW/Anetheron#39]
I am one of many who has lost all their chars whipped today. i hope to see this roll back soon but me keeping all the work and progress i have gotten done. Today was a big day for my Facade

**Comment by alficuesta** [comment]
the same happened to me today i logged in and had my character with no skills no profession no riding skills just my  lvl please fix that

**Comment by alficuesta** [comment]
btw my character is matrox
