### ISSUE TITLE
Honor Point didnt refund.

### ISSUE THREAD

**Issue by morris9595** [AnetheronWoW/Anetheron#47]
After buying PvP items, and decided to sell it back. But its bugged. It can be resell to npc

**Comment by Veliicelis** [comment]
None of the honor, or emblems, or any token based currencies refund to vendors at the moment

**Comment by ATTtheGM** [comment]
Open a ticket if happens once again. Worked for me even in that period.

**Comment by Veliicelis** [comment]
https://www.twitch.tv/videos/153920316
