### ISSUE TITLE
[Mob]Silithid Swarm too much HP

### ISSUE THREAD

**Issue by Schnockers** [AnetheronWoW/Anetheron#6]
These little Bugs called "Silithid Swarm" from the quest "Egg Hunt" in Barrens have way too much HP. As I only see % I noticed it took over 1k Damage to kill them. They are usually just spawn when you loot the mounds to get the eggs for that quest.

**Comment by PredatorAnetheron** [comment]
Invalid, mob has between 531- 573 hp
