### ISSUE TITLE
 Lock Boxes disappearing without any loot?

### ISSUE THREAD

**Issue by TheUltimate1080** [AnetheronWoW/Anetheron#68]
I am playing a rouge like I usually do with my first character on any server; Around Lv 26ish I head to Thousand Needles to pickpocket Lock Boxes to then open to raise my Lock-picking Skill. However, I have now opened a couple of Lock Boxes now, and when I go to open the unlocked boxes they disappear from my inventory without giving me anything. Is this a bug or possible an addon messing something up. I am running the addons; AtlasLoot, Bagnon, Critline, Bartender, and X-Loot. Any info would be kindly appreciated.

**Comment by ATTtheGM** [comment]
Probably because they were empty. No item have a 100% drop chance.
