### ISSUE TITLE
Mending Fences

### ISSUE THREAD

**Issue by Hokraa** [AnetheronWoW/Anetheron#69]
The "Mending Fences" quest in Storm Peaks seems to be bugged.  I have the Charm of the Earth and a boulder in my inventory and I've successfully used the quest items to kill the 5 giants, but when I try to target Fjorn, it says invalid target.  Since this is part of the Sons of Hodir quest line, it is important that this quest be fixed in order to begin earning rep for the Sons of Hodir.  Thanks.

**Comment by ATTtheGM** [comment]
Fjorn can not be targeted with the quest item, you have to normally kill him with the help of those little companions gained from 5x giants.
