### ISSUE TITLE
[Death Knight] "no runes available"

### ISSUE THREAD

**Issue by Veliicelis** [AnetheronWoW/Anetheron#72]

**Comment by Veliicelis** [comment]
On frequent occasion i'll get the above error trying to use an ability, but despite the message it always occurs with at least 4 runes available, AND the ones I want to use available. Once the last of the 6 regen, it seems to fix, as if I'm trying to death strike, frost/unh rune set 1 wont work until rune set 2 regen, and I USE rune set 2. This obviously is also a bug, as the runes are designed to prioritize left to right, in consumption for organization and quality of life purposes.

**Comment by ATTtheGM** [comment]
Can not be reproduced, please try providing us a video where we can see the entire issue, so we can work on it. Thank you.

**Comment by Veliicelis** [comment]
I have not been able to recreate this glitch outside of a raid, and unfortunately, that means the next time I can record it is Sunday if we do get to raid, or Mon under the same circumstance. I DO have a 2 hr long video of an ICC run recorded, that would also show a ton of the ICC bugs I have a separate thread on if you would like that here.
